kiegroup/lienzo-tests

- src/test/java/com/ait/lienzo/client/core/shape/wires/SelectionManagerTest.java
Should be merged with https://github.com/kiegroup/lienzo-core/pull/10
> Disable select action for Middle and Right mouse buttons

- src/main/java/com/ait/lienzo/test/settings/DefaultSettingsHolder.java
- src/main/java/com/ait/lienzo/test/stub/overlays/ShadowJSO.java
Hey @hasys , 
Just added the missing overlay in order to be able to test the shadow attributes from Stunner. 
Thanks!
> JBPM-6391: Added missing stub class for the overlay ShadowJSO

- src/test/java/com/ait/lienzo/client/core/shape/wires/handlers/impl/WiresDockingControlImplTest.java
Inserting tests for `WiresDockingControlImpl`.
Tests related to PR https://github.com/kiegroup/lienzo-core/pull/8
@romartin 
@LuboTerifaj 
@hasys
> JBPM-6178 Stunner - Docking issues

- src/main/java/com/ait/lienzo/test/stub/Attributes.java
- src/test/java/com/ait/lienzo/client/core/shape/MultiPathTest.java
https://issues.jboss.org/browse/JBPM-7129
All this PR's are related to this task:
lienzo-core:
https://github.com/kiegroup/lienzo-core/pull/18
lienzo-tests:
This PR
kie-wb-common
https://github.com/kiegroup/kie-wb-common/pull/1641
> JBPM-7129: Stunner - Allow optional size constraints for shapes

- src/test/java/com/ait/lienzo/client/core/shape/wires/SelectionManagerTest.java
- src/test/java/com/ait/lienzo/client/core/shape/wires/handlers/WiresShapeHandlerImplTest.java
- src/test/java/com/ait/lienzo/client/core/shape/wires/handlers/impl/WiresCompositeShapeHandlerTest.java
See https://issues.jboss.org/browse/JBPM-7118
Before:
After:
---
Part of an ensemble:
- https://github.com/kiegroup/lienzo-core/pull/19
- https://github.com/kiegroup/lienzo-tests/pull/15
- https://github.com/kiegroup/kie-wb-common/pull/1675
> JBPM-7118: Stunner - Mediators (zoom,pan) not working properly

- src/test/java/com/ait/lienzo/client/core/shape/wires/SelectionManagerTest.java
- src/test/java/com/ait/lienzo/client/core/shape/wires/handlers/WiresShapeHandlerImplTest.java
- src/test/java/com/ait/lienzo/client/core/shape/wires/handlers/impl/WiresCompositeShapeHandlerTest.java
See https://issues.jboss.org/browse/RHPAM-838
---
Cherry picked from https://github.com/kiegroup/lienzo-tests/pull/15
---
Part of an ensemble:
- https://github.com/kiegroup/lienzo-core/pull/23
- https://github.com/kiegroup/lienzo-tests/pull/19
- https://github.com/kiegroup/kie-wb-common/pull/1702
> [7.7.x] RHPAM-838 (JBPM-7118): Stunner - Mediators (zoom,pan) not working properly

- src/test/java/com/ait/lienzo/client/core/shape/wires/WiresManagerTest.java
Hey @hasys @manstis 
PS: Still missing to add tests here, will keep working on it. But his makes the build work... :)
Related PRs:
- https://github.com/kiegroup/lienzo-core/pull/21
- https://github.com/kiegroup/kie-wb-common/pull/1685
Thanks!
> JBPM-5462: Fixings tests

- src/test/java/com/ait/lienzo/client/core/shape/wires/WiresManagerTest.java
Hey @hasys 
This is the cherry-pick of https://github.com/kiegroup/lienzo-tests/pull/18 into `7.7.x`
**Depends on** https://github.com/kiegroup/lienzo-core/pull/29
Related to https://github.com/kiegroup/kie-wb-common/pull/1749
Thanks!
> [7.7.x] RHPAM-427: Fixings tests

- src/test/java/com/ait/lienzo/client/core/image/ImageProxyTest.java
Hey @hasys 
This is the test for https://github.com/kiegroup/lienzo-core/pull/31
Thanks!
> JBPM-7244: ImageProxy - test destroy method.

- src/test/java/com/ait/lienzo/client/core/shape/wires/WiresConnectorTest.java
- src/test/java/com/ait/lienzo/client/core/shape/wires/suite/WiresTestSuite.java
Hey @hasys 
This is the cherry-pick for https://github.com/kiegroup/lienzo-tests/pull/23
It **depends on** https://github.com/kiegroup/lienzo-core/pull/33
Thanks!
> JBPM-7272 & JBPM-7269: Fixed errors once removing some nodes

- src/test/java/com/ait/lienzo/client/core/shape/wires/SelectionManagerTest.java
See:
- https://github.com/ahome-it/lienzo-core/pull/218
- https://issues.jboss.org/browse/JBPM-7118
---
No feature is being added by this PR, and no behavior is being broken. I'm just syncing the PR with the blessed repository.
Do not merge before getting the https://github.com/ahome-it/lienzo-tests/pull/22 merged.
---
Part of an ensemble:
- https://github.com/kiegroup/lienzo-core/pull/26
- https://github.com/kiegroup/lienzo-tests/pull/20
> JBPM-7118: Stunner - Mediators (zoom,pan) not working properly (2)

- src/test/java/com/ait/lienzo/client/widget/LienzoHandlerManagerTest.java
This PR check if the pressed mouse buttons is recognized correctly in the mouse down handler
@romartin would you mind to have a look?
Ensemble:
- #27
- kiegroup/lienzo-core#43
> Check pressed mouse button in MouseDownHandler

- src/test/java/com/ait/lienzo/client/core/shape/wires/handlers/WiresShapeHandlerImplTest.java
Inserting tests for PR https://github.com/kiegroup/lienzo-core/pull/42
> [WIP] JBPM-7332 Performance improvements: Remove Layer batch()/draw() and calls

- src/test/java/com/ait/lienzo/client/core/shape/wires/handlers/impl/AbstractWiresControlTest.java
- src/test/java/com/ait/lienzo/client/core/shape/wires/handlers/impl/WiresDockingControlImplTest.java
- src/test/java/com/ait/lienzo/client/core/shape/wires/handlers/impl/WiresShapeControlImplTest.java
Tests for PR https://github.com/kiegroup/lienzo-core/pull/44
@romartin 
@hasys 
@LuboTerifaj
> JBPM-6882 Inserting tests for WiresShapeControlImpl 

- src/test/java/com/ait/lienzo/client/core/image/ImageElementProxyTest.java
- src/test/java/com/ait/lienzo/client/core/image/ImageStripsTest.java
- src/test/java/com/ait/lienzo/client/core/image/ImageTest.java
- src/test/java/com/ait/lienzo/client/core/suite/LienzoCoreTestSuite.java
- src/test/java/com/ait/lienzo/client/core/suite/WiresTestSuite.java
- src/test/java/com/ait/lienzo/test/suite/TestSuite.java
Hey @hasys 
Here are some tests for https://github.com/kiegroup/lienzo-core/pull/48
Thanks!
> [7.7.x] RHPAM-1281: Support for image strips - Tests

- src/test/java/com/ait/lienzo/test/LienzoCoreAttributesTest.java
@romartin Please, check if the tests is good. Thank you!! P.S.: I didn't know what was the correct Copyright header so I copied from another file and changed the year.
> Tests for HiDPI attribute in LienzoCore.

- src/test/java/com/ait/lienzo/test/LienzoCoreAttributesTest.java
(cherry picked from commit d74cb60e0c52fab8684758e9012e9cfa8c740f4a)
Depends on https://github.com/kiegroup/lienzo-core/pull/53
> Tests for HiDPI attribute in LienzoCore

- src/test/java/com/ait/lienzo/client/core/shape/wires/SelectionManagerTest.java
- src/test/java/com/ait/lienzo/client/core/shape/wires/handlers/impl/AbstractWiresControlTest.java
- src/test/java/com/ait/lienzo/client/core/shape/wires/handlers/impl/WiresCompositeControlImplTest.java
- src/test/java/com/ait/lienzo/client/core/shape/wires/handlers/impl/WiresControlPointHandlerImplTest.java
- src/test/java/com/ait/lienzo/client/core/shape/wires/handlers/impl/WiresParentPickerControlImplTest.java
- src/test/java/com/ait/lienzo/client/core/shape/wires/handlers/impl/WiresShapeControlImplTest.java
- src/test/java/com/ait/lienzo/client/core/suite/WiresTestSuite.java
Hey @hasys 
Here are the tests for https://github.com/kiegroup/lienzo-core/pull/54
Thanks!
> JBPM-7022: Stunner - not possible to move Selected nodes in some conditions

- src/test/java/com/ait/lienzo/client/core/shape/wires/WiresConnectorTest.java
- src/test/java/com/ait/lienzo/client/core/shape/wires/WiresManagerTest.java
- src/test/java/com/ait/lienzo/client/core/shape/wires/WiresShapeControlHandleListTest.java
- src/test/java/com/ait/lienzo/client/core/shape/wires/WiresShapeTest.java
- src/test/java/com/ait/lienzo/client/core/shape/wires/handlers/WiresShapeHandlerImplTest.java
- src/test/java/com/ait/lienzo/client/core/shape/wires/handlers/impl/WiresCompositeControlImplTest.java
- src/test/java/com/ait/lienzo/client/core/shape/wires/handlers/impl/WiresConnectorControlImplTest.java
- src/test/java/com/ait/lienzo/client/core/shape/wires/handlers/impl/WiresConnectorHandlerImplTest.java
- src/test/java/com/ait/lienzo/client/core/shape/wires/handlers/impl/WiresControlPointHandlerImplTest.java
- src/test/java/com/ait/lienzo/client/core/shape/wires/handlers/impl/WiresParentPickerControlImplTest.java
- src/test/java/com/ait/lienzo/client/core/shape/wires/handlers/impl/WiresShapeControlImplTest.java
- src/test/java/com/ait/lienzo/client/core/suite/WiresTestSuite.java
Hey @hasys @tiagodolphine 
This is the continuation of https://github.com/kiegroup/lienzo-tests/pull/37 but targeting now `master` branch.
I've squashed all work from the PR referenced above and rebased with master, so it includes all comments you previously said as well.
@hasys still missing to improve test coverage here, working on it. Rather than this, everything should be ok.
It **depends on** https://github.com/kiegroup/lienzo-core/pull/56
Thanks!
> JBPM-7450: Wires Connectors & Bendpoints - Tests

- src/test/java/com/ait/lienzo/client/core/shape/wires/handlers/impl/WiresConnectorControlImplTest.java
Here are the tests to https://github.com/kiegroup/lienzo-core/pull/57
@LuboTerifaj
@wmedvede (adding you to help on the review since @romartin is on PTO)
related:
kiegroup/kie-wb-common#2012
https://github.com/kiegroup/lienzo-core/pull/57
> JBPM-6883 Stunner - can't move with bend points

- src/test/java/com/ait/lienzo/client/core/shape/MultiPathTest.java
- src/test/java/com/ait/lienzo/client/core/shape/wires/BackingColorMapUtilsTest.java
- src/test/java/com/ait/lienzo/client/core/shape/wires/WiresContainerTest.java
- src/test/java/com/ait/lienzo/client/core/shape/wires/WiresManagerTest.java
- src/test/java/com/ait/lienzo/client/core/shape/wires/WiresShapeControlHandleListTest.java
- src/test/java/com/ait/lienzo/client/core/shape/wires/WiresShapeTest.java
- src/test/java/com/ait/lienzo/client/core/shape/wires/handlers/impl/AbstractWiresControlTest.java
- src/test/java/com/ait/lienzo/client/core/shape/wires/handlers/impl/AlignAndDistributeControlImplTest.java
- src/test/java/com/ait/lienzo/client/core/shape/wires/handlers/impl/WiresCompositeControlImplTest.java
- src/test/java/com/ait/lienzo/client/core/shape/wires/handlers/impl/WiresContainmentControlImplTest.java
- src/test/java/com/ait/lienzo/client/core/shape/wires/handlers/impl/WiresDockingControlImplTest.java
- src/test/java/com/ait/lienzo/client/core/shape/wires/handlers/impl/WiresParentPickerControlImplTest.java
- src/test/java/com/ait/lienzo/client/core/shape/wires/handlers/impl/WiresShapeControlImplTest.java
- src/test/java/com/ait/lienzo/client/core/shape/wires/handlers/impl/WiresShapeLocationControlImplTest.java
- src/test/java/com/ait/lienzo/client/core/shape/wires/picker/ColorMapBackedPickerTest.java
- src/test/java/com/ait/lienzo/client/core/suite/WiresTestSuite.java
Fix tests and cherry pick c23e60ff95d880ca0f35c1d49a8050cc2b975dba 7a982c0ba27a1af223de9017bc5f378d8dd9fb1e
Related https://github.com/kiegroup/lienzo-core/pull/52
@romartin
> JBPM-7027 Stunner - docking event to the specific edge of activity 

- src/test/java/com/ait/lienzo/client/core/shape/wires/util/WiresConnectorLabelFactoryTest.java
- src/test/java/com/ait/lienzo/client/core/shape/wires/util/WiresConnectorLabelTest.java
Hey @hasys @tiagodolphine 
See https://issues.jboss.org/browse/JBPM-5566
Depends on https://github.com/kiegroup/lienzo-core/pull/59
Thanks!
> JBPM-5566: [Wires] Labels on connectors - Tests

- src/test/java/com/ait/lienzo/client/core/shape/wires/handlers/impl/WiresConnectorHandlerImplTest.java
Tests for: https://github.com/kiegroup/lienzo-core/pull/66
@manstis
> Tests - Check whether the connector line has control points enabled

- src/main/java/com/ait/lienzo/test/settings/DefaultSettingsHolder.java
- src/main/java/com/ait/lienzo/test/stub/overlays/DragBoundsJSO.java
- src/test/java/com/ait/lienzo/client/core/mediator/MouseWheelZoomMediatorTest.java
- src/test/java/com/ait/lienzo/client/core/shape/wires/handlers/WiresShapeHandlerImplTest.java
- src/test/java/com/ait/lienzo/client/core/shape/wires/handlers/impl/WiresConnectorHandlerImplTest.java
- src/test/java/com/ait/lienzo/client/core/shape/wires/picker/ColorMapBackedPickerTest.java
- src/test/java/com/ait/lienzo/client/core/suite/LienzoCoreTestSuite.java
- src/test/java/com/ait/lienzo/client/widget/panel/LienzoBoundsPanelTest.java
- src/test/java/com/ait/lienzo/client/widget/panel/impl/BoundsProviderFactoryTest.java
- src/test/java/com/ait/lienzo/client/widget/panel/impl/PreviewLayerDecoratorTest.java
- src/test/java/com/ait/lienzo/client/widget/panel/impl/PreviewLayerTest.java
- src/test/java/com/ait/lienzo/client/widget/panel/impl/PreviewPanelTest.java
- src/test/java/com/ait/lienzo/client/widget/panel/impl/ScalablePanelTest.java
- src/test/java/com/ait/lienzo/client/widget/panel/mediators/BoundaryTransformMediatorTest.java
- src/test/java/com/ait/lienzo/client/widget/panel/mediators/RestrictedMousePanMediatorTest.java
- src/test/java/com/ait/lienzo/client/widget/panel/scrollbars/ScrollBarsTest.java
- src/test/java/com/ait/lienzo/client/widget/panel/scrollbars/ScrollBoundsTest.java
- src/test/java/com/ait/lienzo/client/widget/panel/scrollbars/ScrollPositionTest.java
- src/test/java/com/ait/lienzo/client/widget/panel/scrollbars/ScrollUITest.java
- src/test/java/com/ait/lienzo/client/widget/panel/scrollbars/ScrollablePanelHandlerTest.java
- src/test/java/com/ait/lienzo/client/widget/panel/scrollbars/ScrollablePanelTest.java
Hey @hasys 
These are the fixes for making all tests work (regression), still working on the new ones, sorry will provide ASAP, but at least you can start the review.
Depends on https://github.com/kiegroup/lienzo-core/pull/70
Thanks!
> JBPM-5536: Lienzo Panel & implementations - Tests

- src/test/java/com/ait/lienzo/client/core/shape/wires/handlers/impl/WiresDockingControlImplTest.java
- src/test/java/com/ait/lienzo/client/core/shape/wires/handlers/impl/WiresShapeControlImplTest.java
Hey @hasys 
These are the tests for https://github.com/kiegroup/lienzo-core/pull/82
Thanks!
> [7.14.x] RHPAM-1809: Tests for issues related to docking.

- src/test/java/com/ait/lienzo/client/core/shape/wires/handlers/impl/WiresDockingControlImplTest.java
- src/test/java/com/ait/lienzo/client/core/shape/wires/handlers/impl/WiresShapeControlImplTest.java
Hey @hasys  @tiagodolphine 
Tests for https://github.com/kiegroup/lienzo-core/pull/78
Thanks!
> JBPM-8044: [Stunner] Docking is not working when the preview panel is opened.

- src/test/java/com/ait/lienzo/client/core/shape/wires/DefaultSelectionListenerTest.java
- src/test/java/com/ait/lienzo/client/core/shape/wires/SelectionManagerTest.java
- src/test/java/com/ait/lienzo/client/core/shape/wires/WiresConnectorTest.java
- src/test/java/com/ait/lienzo/client/core/shape/wires/WiresContainerTest.java
- src/test/java/com/ait/lienzo/client/core/shape/wires/WiresManagerTest.java
- src/test/java/com/ait/lienzo/client/core/shape/wires/WiresShapeTest.java
- src/test/java/com/ait/lienzo/client/core/shape/wires/handlers/impl/ShapeControlUtilsTest.java
- src/test/java/com/ait/lienzo/client/core/shape/wires/handlers/impl/WiresConnectorControlImplTest.java
- src/test/java/com/ait/lienzo/client/core/shape/wires/handlers/impl/WiresConnectorControlPointBuilderTest.java
- src/test/java/com/ait/lienzo/client/core/shape/wires/handlers/impl/WiresConnectorEventFunctionsTest.java
- src/test/java/com/ait/lienzo/client/core/shape/wires/handlers/impl/WiresConnectorHandlerImplTest.java
- src/test/java/com/ait/lienzo/client/core/suite/WiresTestSuite.java
- src/test/java/com/ait/lienzo/client/widget/panel/LienzoBoundsPanelTest.java
- src/test/java/com/ait/lienzo/client/widget/panel/impl/PreviewPanelTest.java
- src/test/java/com/ait/lienzo/client/widget/panel/impl/ScalablePanelTest.java
Hey @tiagodolphine  @hasys 
Here are the tests for https://github.com/kiegroup/lienzo-core/pull/79
Thanks!
> JBPM-8067: Magnets & connector bendpoints are not working with the scrollable lienzo panel.

- src/test/java/com/ait/lienzo/client/core/shape/wires/OptionalBoundsTest.java
- src/test/java/com/ait/lienzo/client/core/shape/wires/handlers/impl/WiresShapeControlImplTest.java
- src/test/java/com/ait/lienzo/client/core/shape/wires/handlers/impl/WiresShapeLocationBoundsTest.java
- src/test/java/com/ait/lienzo/client/core/suite/WiresTestSuite.java
- src/test/java/com/ait/lienzo/client/widget/panel/LienzoBoundsPanelTest.java
- src/test/java/com/ait/lienzo/client/widget/panel/impl/PreviewPanelTest.java
- src/test/java/com/ait/lienzo/client/widget/panel/impl/ScalablePanelTest.java
Hey @hasys 
Tests for https://github.com/kiegroup/lienzo-core/pull/83
Thanks!
> JBPM-8111: Wires - Tests for shape location constraints.

- src/test/java/com/ait/lienzo/client/core/shape/TextTruncateWrapperTest.java
The tests for the PR: https://github.com/kiegroup/lienzo-core/pull/84
> DROOLS-2697: [DMN Designer] Improve readability of node labels

- src/test/java/com/ait/lienzo/client/core/shape/wires/SelectedItemsTest.java
- src/test/java/com/ait/lienzo/client/core/shape/wires/SelectionManagerTest.java
- src/test/java/com/ait/lienzo/client/core/shape/wires/WiresManagerTest.java
Hi @tiagodolphine, @LuboTerifaj there is test for non-trivial change from https://github.com/kiegroup/lienzo-core/pull/89
CC @romartin 
Assembly:
https://github.com/kiegroup/lienzo-core/pull/89
https://github.com/kiegroup/lienzo-tests/pull/67
> Fixing issues reported by findbug plugin

- src/test/java/com/ait/lienzo/client/core/shape/wires/SelectionManagerTest.java
JIRA: https://issues.jboss.org/browse/JBPM-6814
> [JBPM-6814 ] Stunner - selected objects can't be moved more than one time without reselection

- src/test/java/com/ait/lienzo/client/widget/panel/impl/PreviewPanelTest.java
- src/test/java/com/ait/lienzo/client/widget/panel/impl/ScalablePanelTest.java
- src/test/java/com/ait/lienzo/client/widget/panel/mediators/PanelMediatorsTest.java
- src/test/java/com/ait/lienzo/client/widget/panel/mediators/PanelPreviewMediatorTest.java
- src/test/java/com/ait/lienzo/client/widget/panel/mediators/RestrictedMousePanMediatorTest.java
- src/test/java/com/ait/lienzo/client/widget/panel/scrollbars/ScrollablePanelTest.java
- src/test/java/com/ait/lienzo/client/widget/panel/util/PanelTransformUtilsTests.java
Hey @hasys @jomarko 
Here are the tests for https://github.com/kiegroup/lienzo-core/pull/92
Thanks!
> JBPM-7443 & JBPM-7429: Stunner - Tests for zooming and panning improvements

- src/test/java/com/ait/lienzo/client/core/shape/TextBoundsWrapTest.java
- src/test/java/com/ait/lienzo/client/core/shape/TextLineBreakTruncateWrapperTest.java
- src/test/java/com/ait/lienzo/client/core/shape/TextTruncateWrapperTest.java
- src/test/java/com/ait/lienzo/client/core/shape/wires/WiresShapeTest.java
- src/test/java/com/ait/lienzo/client/core/shape/wires/layout/AbstractContainerLayoutTest.java
- src/test/java/com/ait/lienzo/client/core/shape/wires/layout/direction/DirectionContainerLayoutTest.java
- src/test/java/com/ait/lienzo/client/core/shape/wires/layout/direction/HorizontalLayoutFactoryTest.java
- src/test/java/com/ait/lienzo/client/core/shape/wires/layout/direction/VerticalLayoutFactoryTest.java
- src/test/java/com/ait/lienzo/client/core/shape/wires/layout/label/LabelContainerLayoutTest.java
- src/test/java/com/ait/lienzo/client/core/shape/wires/layout/size/SizeConstraintsContainerLayoutTest.java
- src/test/java/com/ait/lienzo/client/core/shape/wires/util/WiresConnectorLabelTest.java
Tests for
https://github.com/kiegroup/lienzo-core/pull/94
@romartin 
@LuboTerifaj
> JBPM-6454 Stunner - rethink text wrapping and fonts for nodes 

- src/test/java/com/ait/lienzo/client/widget/panel/scrollbars/ScrollablePanelTest.java
Part of an ensemble:
* https://github.com/kiegroup/lienzo-core/pull/95
* https://github.com/kiegroup/lienzo-tests/pull/75
> AF-1936: Unexpected error when deleting project with Business Process

- src/main/java/com/ait/lienzo/test/stub/overlays/Point2DJSO.java
- src/test/java/com/ait/lienzo/client/core/shape/toolbox/GroupItemTest.java
- src/test/java/com/ait/lienzo/client/core/shape/toolbox/grid/AutoGridTest.java
- src/test/java/com/ait/lienzo/client/core/shape/toolbox/grid/FixedLayoutGridTest.java
- src/test/java/com/ait/lienzo/client/core/shape/toolbox/items/decorator/DecoratorsFactoryTest.java
- src/test/java/com/ait/lienzo/client/core/shape/toolbox/items/impl/ButtonGridItemImplTest.java
- src/test/java/com/ait/lienzo/client/core/shape/toolbox/items/impl/ButtonItemImplTest.java
- src/test/java/com/ait/lienzo/client/core/shape/toolbox/items/impl/FocusableGroupTest.java
- src/test/java/com/ait/lienzo/client/core/shape/toolbox/items/impl/GroupImplTest.java
- src/test/java/com/ait/lienzo/client/core/shape/toolbox/items/impl/ItemGridImplTest.java
- src/test/java/com/ait/lienzo/client/core/shape/toolbox/items/impl/ItemImplTest.java
- src/test/java/com/ait/lienzo/client/core/shape/toolbox/items/impl/ItemsToolboxHighlightTest.java
- src/test/java/com/ait/lienzo/client/core/shape/toolbox/items/impl/ToolboxImplTest.java
- src/test/java/com/ait/lienzo/client/core/shape/toolbox/items/impl/WiresShapeToolboxTest.java
- src/test/java/com/ait/lienzo/client/core/shape/toolbox/items/tooltip/PrimitiveTextTooltipTest.java
- src/test/java/com/ait/lienzo/client/core/shape/toolbox/items/tooltip/TextTooltipItemImplTest.java
- src/test/java/com/ait/lienzo/client/core/shape/toolbox/items/tooltip/ToolboxTextTooltipTest.java
- src/test/java/com/ait/lienzo/client/core/shape/wires/handlers/WiresShapeHandlerImplTest.java
- src/test/java/com/ait/lienzo/client/core/shape/wires/handlers/impl/WiresDockingControlImplTest.java
- src/test/java/com/ait/lienzo/client/core/shape/wires/handlers/impl/WiresShapeHighlightControlTest.java
- src/test/java/com/ait/lienzo/client/core/shape/wires/proxy/WiresConnectorProxyTest.java
- src/test/java/com/ait/lienzo/client/core/shape/wires/proxy/WiresDragProxyTest.java
- src/test/java/com/ait/lienzo/client/core/shape/wires/proxy/WiresShapeProxyTest.java
- src/test/java/com/ait/lienzo/client/core/util/GeometryTest.java
Hey @hasys 
Here are the tests for https://github.com/kiegroup/lienzo-core/pull/97
It depends on:
https://github.com/kiegroup/lienzo-core/pull/97
https://github.com/kiegroup/kie-wb-common/pull/3012
Thanks!
> RHPAM-2319: Stunner - Users don't understand how to create lines between nodes

- Jenkinsfile
- Jenkinsfile.downstream
- Jenkinsfile.downstream.production
BXMSPROD-592
depends on:
- https://github.com/kiegroup/jenkins-pipeline-shared-libraries/pull/5
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1160
> BXMSPROD-592 upstream and downstream jenkins configuration

- src/test/java/com/ait/lienzo/client/widget/panel/mediators/PanelPreviewMediatorTest.java
Hey @tiagobento 
Tests updated for https://github.com/kiegroup/lienzo-core/pull/101
Thannks!
> JBPM-8386: Preview Panel mediator tests updated.

- src/test/java/com/ait/lienzo/client/widget/panel/scrollbars/ScrollablePanelHandlerTest.java
@romartin , @inodeman : Could you review this PR please?
> KOGITO-1196: Editor goes back horizontally when diagram is bigger than default

- src/test/java/com/ait/lienzo/client/core/shape/toolbox/ToolboxVisibilityExecutorsTest.java
- src/test/java/com/ait/lienzo/client/core/shape/wires/SelectionManagerTest.java
- src/test/java/com/ait/lienzo/client/core/shape/wires/handlers/impl/WiresShapeControlImplTest.java
- src/test/java/com/ait/lienzo/client/core/shape/wires/handlers/impl/WiresShapeControlUtilsTest.java
- src/test/java/com/ait/lienzo/client/widget/panel/scrollbars/ScrollablePanelHandlerTest.java
@romartin, @inodeman : Please, could you review this PR?
See https://issues.redhat.com/browse/JBPM-9175
Assembly with:
* https://github.com/kiegroup/kie-wb-common/pull/3319
* https://github.com/kiegroup/lienzo-core/pull/111
* https://github.com/kiegroup/lienzo-tests/pull/94
> JBPM-9175: Stunner - Usability improvements around selection / drag capabilities

- pom.xml
**Upgrade JDK 11 + GWT 2.9**
Feel free to comment and/or raise any concerns.
This PR continues the work done in 
- https://github.com/kiegroup/appformer/pull/1030
- https://github.com/kiegroup/appformer/pull/1039
Thanks guys for that!
**JIRA**:
[AF-1799](https://issues.redhat.com/browse/AF-1799)
**Parent Pull Request**:
- https://github.com/kiegroup/lienzo-core/pull/134
<details>
<summary>
How to retest this PR or trigger a specific build:
</summary>
* <b>a pull request</b> please add comment: <b>Jenkins retest this</b>
* <b>a full downstream build</b> please add comment: <b>Jenkins run fdb</b>
* <b>a compile downstream build</b> please  add comment: <b>Jenkins run cdb</b>
* <b>a full production downstream build</b> please add comment: <b>Jenkins execute product fdb</b>
* <b>an upstream …
> AF-1799: Upgrade JDK 11 + GWT 2.9

- pom.xml
This reverts commit f3458871d937b0e1a908e51638154c1fea1ec47f.
**JIRA**: 
https://issues.redhat.com/browse/RHPAM-4505
**referenced Pull Requests**: 
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2068
* https://github.com/kiegroup/kie-wb-common/pull/3776
* https://github.com/kiegroup/kie-wb-distributions/pull/1191
* https://github.com/kiegroup/drools-wb/pull/1556
Changes by RHPAM-4387 in `jbpm-wb` were already reverted in 7.67.x
<details>
<summary>
How to replicate CI configuration locally?
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain …
> [7.67.x] [RHPAM-4505] Revert "RHPAM-4387 xercesImpl to 2.12.2 (#137)"

- pom.xml
This reverts commit 80e875b6e62515a2794ed87b317e842369da12d2.
**JIRA**: 
https://issues.redhat.com/browse/RHPAM-4505
**referenced Pull Requests**: 
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2069
* https://github.com/kiegroup/kie-wb-common/pull/3777
* https://github.com/kiegroup/kie-wb-distributions/pull/1192
* https://github.com/kiegroup/drools-wb/pull/1557
Changes by RHPAM-4387 in `jbpm-wb` were already reverted in 7.67.x-blue
<details>
<summary>
How to replicate CI configuration locally?
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain …
> [7.67.x-blue] [RHPAM-4505] Revert "RHPAM-4387 xercesImpl to 2.12.2 (#138)"
